name: Main

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.*'
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build packages
    if: ${{ github.event_name == 'release' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: ubuntu-latest
            CMD_BUILD: poetry run pyinstaller -F -w -n hardwario cli.py
            OUT_FILE_NAME: hardwario
            ASSET_MIME: application/octet-stream
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                poetry run pyinstaller -F -w -n hardwario cli.py &&
                cd dist/ &&
                zip -r9 hardwario hardwario.app/
            OUT_FILE_NAME: hardwario.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: poetry run pyinstaller -F -w -n hardwario cli.py
            OUT_FILE_NAME: hardwario.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./dist/${{ matrix.OUT_FILE_NAME}}
